### ISSUE TITLE
添加返回条

### ISSUE THREAD

**Issue by Linfye** [Linfye/xjn#4]
如剧中所示每个页面右上角应有一个返回条，可以返回上一个页面或者返回主页面，计划在未来添加。

**Comment by Yousone** [comment]
请求认领

**Comment by Yousone** [comment]
那三条横杠不是返回条，返回条不长这样。应该是下拉菜单，用来管理登录和其他功能的。

**Comment by Linfye** [comment]
但是本网页没有登录功能，暂定为一个下拉菜单，选项为返回上一页面或者返回主页，你也可以添加其他你觉得必要的功能

**Comment by Linfye** [comment]
Closed this issue. Looking forward to your next contrubution. :)
